buildpack: https://github.com/pkgr/pkgr-noop-buildpack
before_install: scripts/preinstall
after_install: scripts/postinstall
targets:
  ubuntu-12.04:
  ubuntu-14.04:
    build_dependencies:
      - curl
  doesnotexist:
maintainer: hello@example.com
